[global]
calc_pattern = 'CalcXXXX'

loglevel = 'DEBUG'
#loglevel = 'INFO'
#loglevel = 'WARNING'
#loglevel = 'ERROR'
#loglevel = 'CRITCAL'

phase = ['prepare', 'calc', 'output']

[CalcXXXX]
rootpath_in = './'
rootpath_out = './'

[CalcXXXX.exec_cond]
years = ['2017', '2018']
cases = ['case0001', 'case0002', 'case0003']

[CalcXXXX.figure_cond]
dirpath_out = './'
xmin = 0
xmax = 5000
ymin = 0
ymax = 5000
title = 'Test figure'
header = 'testfig'

[[CalcXXXX.figure_cond.var]]
fname = 'file1.ctl'
vname = 'val1'
levels = [0.00, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14, 0.16, 0.18, 0.20]

[[CalcXXXX.figure_cond.var]]
fname = 'file2.ctl'
vname = 'val2'
interval = 3
